In [16]:
import math
import numpy as np

In [17]:
def jacobi(matrice,tolval,stopcriterion,n):
    
    
    coefficent = matrice[:,:-1] # coeffiecent
    augmented = matrice[:,-1] #augmented
    
    noveaucoe = coefficent.copy()#copying coefficent
    noveauaug = augmented.copy()#copying augmented 
    for i in range(n):#checking if val is diagonally dominant or not
        offsum = 0#retreiving sum
        diagnonal = np.abs(noveaucoe[i,i])#
        for j in range(n):
            if(i!=j):#if it is not, just get sum of coefficents
                offsum +=np.abs(noveaucoe[i,j])
        if diagnonal < offsum:
            print("not diagonally dominant. Must transform")#if the diagonal is smaller than sum,display this message
            
        
    for i in range(n):
        noveauaug[i]=noveauaug[i]/noveaucoe[i,i]#transforming biasses via dividng them by diagonal element
        for j in range(n):
            if i !=j:# avoiding redundant operations in main loop
                noveaucoe[i,j]= noveaucoe[i,j]/noveaucoe[i,i]
    newval=np.ones(n)
    oldval=np.ones(n)        
    error=10#starting new while loop
    while(error>tolval):#main loop for our iterative process
        error = 0#initalizer of error
        for i in range(n):
            oldval[i]=newval[i]#store current approximations
            newval[i] = noveauaug[i]#storing current approximations
        for i in range(n):#loop for calculations
            for j in range(n):
                if(i!=j):
                    newval[i]=newval[i]-noveaucoe[i,j]*oldval[j]
                    
        if stopcriterion == "MAE":#if criterion is MAE
            error = np.mean(np.abs(newval-oldval))
        elif stopcriterion == "RMSE":# if critieion is RMSE
            error = np.sqrt(np.mean(np.abs(newval-oldval)**2))
        else:
            return None
    return newval

In [18]:
def gauss(matrice,tolval,stopcriterion,n):
    coefficent = matrice[:,:-1] # coeffiecent
    augmented = matrice[:,-1] #augmented
    
    noveaucoe = coefficent.copy()
    noveauaug = augmented.copy()
    #checking if dagonaly or not
    for i in range(n):
        offsum = 0
        diagnonal = np.abs(noveaucoe[i,i])
        for j in range(n):
            if(i!=j):
                offsum +=np.abs(noveaucoe[i,j])
        if diagnonal < offsum:
            print("not diagonally dominant. Must transform")
            
    for i in range(n):
        noveauaug[i]=noveauaug[i]/noveaucoe[i,i]
        for j in range(n):
            if(i!=j):
                 noveaucoe[i,j]= noveaucoe[i,j]/ noveaucoe[i,i]
    x=np.ones(n)
    oldval=np.ones(n)
    error = 10#error intializer is assigned to 10
    
    while(error > tolval):
        error=0# initalzatior of error
        oldval=x.copy()
        for i in range(n):
            x[i]=noveauaug[i]#updating current approximations of new x array
            for j in range(n):
                if i!= j:
                    x[i]=x[i]- noveaucoe[i,j]*x[j]#latest avaliable approximations
                    
            #stop criterions
        if stopcriterion == "MAE":
            error = np.mean(np.abs(x-oldval))
        elif stopcriterion == "RMSE":
            error = np.sqrt(np.mean(np.abs(x-oldval)**2))
        else:
            return None   
        
        
    return x

**ADD TRUE MAE AND RMSE FOR BOTH JACOBI AND GAUSS**

In [19]:
#jacobi1
matrice1 = np.array([[3,1,-4],[-2,3,1],[2,0,5]],dtype=float)
matrice1augmented = np.array([[7],[-5],[10]],dtype=float)

augmented1 = np.hstack((matrice1,matrice1augmented))
print(augmented1)
x,y,z=jacobi(augmented1,0.001,"RMSE",3)
eq1=  3*x + 1*y + -4*z
eq2=  -2*x + 3*y + 1*z
eq3=  2*x + 0*y+5*z
print(eq1,eq2,eq3)

[[ 3.  1. -4.  7.]
 [-2.  3.  1. -5.]
 [ 2.  0.  5. 10.]]
not diagonally dominant. Must transform
7.00273281461301 -5.003147819557462 10.002627197837134


In [20]:
#jacbobi 2
matrice1 = np.array([[3,1,-4],[-2,3,1],[2,0,5]],dtype=float)
matrice1augmented = np.array([[7],[-5],[10]],dtype=float)

augmented1 = np.hstack((matrice1,matrice1augmented))

x,y,z=jacobi(augmented1,0.001,"MAE",3)
eq1=  3*x + 1*y + -4*z
eq2=  -2*x + 3*y + 1*z
eq3=  2*x + 0*y+5*z
print(eq1,eq2,eq3)

not diagonally dominant. Must transform
7.00273281461301 -5.003147819557462 10.002627197837134


In [21]:
#jacobi 3
def partial(matrice):
    n =  matrice.shape[0]
    a = matrice.copy()
    for i in range(n):
        maxrow = np.argmax(np.abs(a[i:,i]))+i
        if maxrow !=i:
            a[[i,maxrow]] = a[[maxrow,i]]
        
    return a
        
matrice2 = np.array([[1,-2,4],[8,-3,2],[-1,10,2]],dtype=float)

matrice2augmented = np.array([[6],[2],[4]],dtype=float)

augmented2 = np.hstack((matrice2,matrice2augmented))
print(augmented2)
x2 = partial(augmented2)
x,y,z=jacobi(x2,0.001,"RMSE",3)
eq1=  1*x + -2*y+4*z
eq2=  8*x + -3*y + 2*z
eq3=  -1*x + 10*y+2*z
print(eq1,eq2,eq3)

[[ 1. -2.  4.  6.]
 [ 8. -3.  2.  2.]
 [-1. 10.  2.  4.]]
5.9998828125 2.0001953125000003 4.000273437500001


In [22]:
#jacobi 4
def partial(matrice):
    n =  matrice.shape[0]
    a = matrice.copy()
    for i in range(n):
        maxrow = np.argmax(np.abs(a[i:,i]))+i
        if maxrow !=i:
            a[[i,maxrow]] = a[[maxrow,i]]
        
    return a
        
matrice2 = np.array([[1,-2,4],[8,-3,2],[-1,10,2]],dtype=float)

matrice2augmented = np.array([[6],[2],[4]],dtype=float)

augmented2 = np.hstack((matrice2,matrice2augmented))
x2 = partial(augmented2)
xa,ya,za=jacobi(x2,0.001,"MAE",3)
eq1=  1*xa + -2*ya+4*za
eq2=  8*xa + -3*ya + 2*za
eq3=  -1*xa + 10*ya+2*za
print(eq1,eq2,eq3)

5.9998828125 2.0001953125000003 4.000273437500001


In [23]:
#gause 1
matrice3 = np.array([[3,1,-4],[-2,3,1],[2,0,5]],dtype=float)
matrice3augmented = np.array([[7],[-5],[10]],dtype=float)

augmented3 = np.hstack((matrice3,matrice3augmented))

x,y,z=gauss(augmented3,0.001,"RMSE",3)
eq1=  3*x + 1*y + -4*z
eq2=  -2*x + 3*y + 1*z
eq3=  2*x + 0*y+5*z
print(eq1,eq2,eq3)

not diagonally dominant. Must transform
7.002476182193646 -5.0004776165899125 10.0


In [24]:
#gauss 2
matrice3 = np.array([[3,1,-4],[-2,3,1],[2,0,5]],dtype=float)
matrice3augmented = np.array([[7],[-5],[10]],dtype=float)

augmented3 = np.hstack((matrice3,matrice3augmented))

x,y,z=gauss(augmented3,0.001,"MAE",3)
eq1=  3*x + 1*y + -4*z
eq2=  -2*x + 3*y + 1*z
eq3=  2*x + 0*y+5*z
print(eq1,eq2,eq3)

not diagonally dominant. Must transform
7.002476182193646 -5.0004776165899125 10.0


In [25]:
#gauss 3
matrice4 = np.array([[1,-2,4],[8,-3,2],[-1,10,2]],dtype=float)
matrice4augmented = np.array([[6],[2],[4]],dtype=float)
augmented4 = np.hstack((matrice4,matrice4augmented))
x4 = partial(augmented4)
x,y,z=gauss(x4,0.001,"MAE",3)
eq1=  1*x + -2*y+4*z
eq2=  8*x + -3*ya + 2*z
eq3=  -1*x + 10*ya+2*z
print(eq1,eq2,eq3)

6.0 2.0009891613769533 4.000201920776368


In [26]:
#gauss 4
matrice4 = np.array([[1,-2,4],[8,-3,2],[-1,10,2]],dtype=float)
matrice4augmented = np.array([[6],[2],[4]],dtype=float)
augmented4 = np.hstack((matrice4,matrice4augmented))
x4 = partial(augmented4)
x,y,z=gauss(x4,0.001,"RMSE",3)
eq1=  1*x + -2*y+4*z
eq2=  8*x + -3*y + 2*z
eq3=  -1*x + 10*y+2*z
print(eq1,eq2,eq3)

6.0 2.0009468099975587 4.000343092041016


In [27]:
import numpy as np

def is_diagonally_dominant(A):
    """
    Checks if a square matrix A is weakly diagonally dominant.
    A(n,n) is diagonally dominant if for all i=1..n,
    |A[i,i]| >= sum(|A[i,j]|) for j != i
    """
    n = A.shape[0]
    for i in range(n):
        diag_element = abs(A[i, i])
        off_diag_sum = 0
        for j in range(n):
            if i != j:
                off_diag_sum += abs(A[i, j])
        
        if diag_element < off_diag_sum:
            return False
    return True

def jacobi(aug_matrix, tol, stop_criterion, max_iter=100):
    """
    Solves a system of linear equations Ax = b using the Jacobi iterative method.

    Args:
        aug_matrix (np.array): The augmented matrix [A|b].
        tol (float): The tolerance threshold for the stopping criterion.
        stop_criterion (str): 'mae' for Mean Absolute Error or 'rmse' for 
                              Root Mean Square Error.
        max_iter (int, optional): Maximum number of iterations. Defaults to 100.

    Returns:
        tuple: (solution_vector, iterations_count)
               Returns (None, 0) if the method cannot proceed (e.g., 0 on diagonal).
    """
    A = aug_matrix[:, :-1]
    b = aug_matrix[:, -1]
    n = len(b)

    # Check for zeros on the diagonal
    if np.any(np.diag(A) == 0):
        print("Error (Jacobi): A diagonal element is zero. Method cannot proceed.")
        return None, 0

    # Check for diagonal dominance
    if not is_diagonally_dominant(A):
        print("\n---------------------------------------------------------")
        print("Warning (Jacobi): The coefficient matrix is not diagonally dominant.")
        print("Convergence is not guaranteed. Proceeding anyway.")
        print("---------------------------------------------------------\n")

    # Initialize solution vector x with ones
    x = np.ones(n)
    x_new = np.zeros(n)
    
    iter_count = 0
    error = float('inf')

    while error > tol and iter_count < max_iter:
        iter_count += 1
        
        # Jacobi iteration formula
        for i in range(n):
            sigma = 0
            for j in range(n):
                if i != j:
                    sigma += A[i, j] * x[j]  # Use values from *previous* iteration (x)
            x_new[i] = (b[i] - sigma) / A[i, i]

        # Calculate error
        diff = x_new - x
        if stop_criterion == 'mae':
            error = np.mean(np.abs(diff))
        elif stop_criterion == 'rmse':
            error = np.sqrt(np.mean(diff**2))
        else:
            raise ValueError("Invalid stop_criterion. Use 'mae' or 'rmse'.")

        # Update x for the next iteration
        x = x_new.copy()

    if iter_count == max_iter and error > tol:
        print(f"Warning (Jacobi): Method failed to converge within {max_iter} iterations.")
        
    return x, iter_count

def gauss_seidel(aug_matrix, tol, stop_criterion, max_iter=100):
    """
    Solves a system of linear equations Ax = b using the Gauss-Seidel iterative method.

    Args:
        aug_matrix (np.array): The augmented matrix [A|b].
        tol (float): The tolerance threshold for the stopping criterion.
        stop_criterion (str): 'mae' for Mean Absolute Error or 'rmse' for 
                              Root Mean Square Error.
        max_iter (int, optional): Maximum number of iterations. Defaults to 100.

    Returns:
        tuple: (solution_vector, iterations_count)
               Returns (None, 0) if the method cannot proceed (e.g., 0 on diagonal).
    """
    A = aug_matrix[:, :-1]
    b = aug_matrix[:, -1]
    n = len(b)

    # Check for zeros on the diagonal
    if np.any(np.diag(A) == 0):
        print("Error (Gauss-Seidel): A diagonal element is zero. Method cannot proceed.")
        return None, 0

    # Check for diagonal dominance
    if not is_diagonally_dominant(A):
        print("\n---------------------------------------------------------")
        print("Warning (Gauss-Seidel): The coefficient matrix is not diagonally dominant.")
        print("Convergence is not guaranteed. Proceeding anyway.")
        print("---------------------------------------------------------\n")

    # Initialize solution vector x with ones
    x = np.ones(n)
    
    iter_count = 0
    error = float('inf')

    while error > tol and iter_count < max_iter:
        iter_count += 1
        x_old = x.copy() # Store old x for error calculation
        
        # Gauss-Seidel iteration formula
        for i in range(n):
            sigma = 0
            for j in range(n):
                if i != j:
                    # Uses *new* x[j] for j < i and *old* x[j] for j > i
                    sigma += A[i, j] * x[j] 
            x[i] = (b[i] - sigma) / A[i, i]

        # Calculate error
        diff = x - x_old
        if stop_criterion == 'mae':
            error = np.mean(np.abs(diff))
        elif stop_criterion == 'rmse':
            error = np.sqrt(np.mean(diff**2))
        else:
            raise ValueError("Invalid stop_criterion. Use 'mae' or 'rmse'.")

    if iter_count == max_iter and error > tol:
        print(f"Warning (Gauss-Seidel): Method failed to converge within {max_iter} iterations.")
        
    return x, iter_count

In [28]:
if __name__ == "__main__":
    # Set numpy print options for clean output
    np.set_printoptions(precision=6, suppress=True)

    # --- Define Matrices and Tolerance ---
    
    # Matrix 1 (from part d)
    aug_matrix_1 = np.array([
        [3,  1, -1, 4],
        [2, -3,  1, 7],
        [1,  0, -2, 5]
    ], dtype=float)

    # Matrix 2 (from part e)
    aug_matrix_2 = np.array([
        [1,  2, -1, 6],
        [8,  3,  2, 2],
        [1, -1,  4, 0]
    ], dtype=float)

    tolerance = 0.001

    # --- Solve System 1 ---
    print("==========================================")
    print("         SOLVING SYSTEM 1")
    print("==========================================")
    print("Augmented Matrix:\n", aug_matrix_1)
    print("Tolerance: ", tolerance, "\n")

    # Jacobi with MAE
    sol, iters = jacobi(aug_matrix_1, tolerance, 'mae')
    print(f"Jacobi (MAE):     Solution {sol} in {iters} iterations")

    # Jacobi with RMSE
    sol, iters = jacobi(aug_matrix_1, tolerance, 'rmse')
    print(f"Jacobi (RMSE):    Solution {sol} in {iters} iterations")

    # Gauss-Seidel with MAE
    sol, iters = gauss_seidel(aug_matrix_1, tolerance, 'mae')
    print(f"Gauss-Seidel (MAE): Solution {sol} in {iters} iterations")

    # Gauss-Seidel with RMSE
    sol, iters = gauss_seidel(aug_matrix_1, tolerance, 'rmse')
    print(f"Gauss-Seidel (RMSE): Solution {sol} in {iters} iterations")

    print("\n")

    # --- Solve System 2 ---
    print("==========================================")
    print("         SOLVING SYSTEM 2")
    print("==========================================")
    print("Augmented Matrix:\n", aug_matrix_2)
    print("Tolerance: ", tolerance, "\n")

    # Jacobi with MAE
    sol, iters = jacobi(aug_matrix_2, tolerance, 'mae')
    print(f"Jacobi (MAE):     Solution {sol} in {iters} iterations")

    # Jacobi with RMSE
    sol, iters = jacobi(aug_matrix_2, tolerance, 'rmse')
    print(f"Jacobi (RMSE):    Solution {sol} in {iters} iterations")

    # Gauss-Seidel with MAE
    sol, iters = gauss_seidel(aug_matrix_2, tolerance, 'mae')
    print(f"Gauss-Seidel (MAE): Solution {sol} in {iters} iterations")

    # Gauss-Seidel with RMSE
    sol, iters = gauss_seidel(aug_matrix_2, tolerance, 'rmse')
    print(f"Gauss-Seidel (RMSE): Solution {sol} in {iters} iterations")

         SOLVING SYSTEM 1
Augmented Matrix:
 [[ 3.  1. -1.  4.]
 [ 2. -3.  1.  7.]
 [ 1.  0. -2.  5.]]
Tolerance:  0.001 

Jacobi (MAE):     Solution [ 1.400247 -2.000765 -1.800335] in 9 iterations
Jacobi (RMSE):    Solution [ 1.400247 -2.000765 -1.800335] in 9 iterations
Gauss-Seidel (MAE): Solution [ 1.400156 -2.000024 -1.799922] in 7 iterations
Gauss-Seidel (RMSE): Solution [ 1.400156 -2.000024 -1.799922] in 7 iterations


         SOLVING SYSTEM 2
Augmented Matrix:
 [[ 1.  2. -1.  6.]
 [ 8.  3.  2.  2.]
 [ 1. -1.  4.  0.]]
Tolerance:  0.001 


---------------------------------------------------------
Warning (Jacobi): The coefficient matrix is not diagonally dominant.
Convergence is not guaranteed. Proceeding anyway.
---------------------------------------------------------

Warning (Jacobi): Method failed to converge within 100 iterations.
Jacobi (MAE):     Solution [-3.624644e+35 -4.180201e+35  5.628848e+33] in 100 iterations

-----------------------------------------------------